//go:build (linux && !android) || (darwin && !ios)

package cli

// Generated companion data for the GH #23 aggregate acceptance ledger.
//
// pibEarlySliceLedger carries PIB-001…PIB-394 (slices S1b, S1, S2, S3, S4, S4b,
// S5 and S6). PIB-395…PIB-567 are NOT restated here: pibS7LedgerRows reads them
// straight out of the twelve accepted S7 category ledgers.
//
// Every identity below was selected as the narrowest body that actually proves
// its row and was checked against the resolver contract. There is no opt-out:
// a row that names no resolvable, body-sensitive target fails the aggregate
// gate. Rows whose only prior evidence was an aggregate wrapper, a skipping
// body or a runtime-named subtest are owned by the `TestPIBRow…` tests, which
// perform the row's own setup and assert the observable §18 names for it.

func pibEarlySliceLedger() map[string]pibLedgerRow {
	return map[string]pibLedgerRow{
		"PIB-001": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "generate"}}},
		"PIB-002": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestAVPGrammarAndSurface", subtest: "AVP-002"}}},
		"PIB-003": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestAVPGrammarAndSurface", subtest: "AVP-003"}}},
		"PIB-004": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareFlagMutexCombinations", subtest: "PIB-004"}}},
		"PIB-005": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareCheckModeFlagMutex", subtest: "PIB-005"}}},
		"PIB-006": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareCheckModeFlagMutex", subtest: "PIB-006"}}},
		"PIB-007": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareFlagMutexCombinations", subtest: "PIB-007"}}},
		"PIB-008": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareFlagMutexCombinations", subtest: "PIB-008"}}},
		"PIB-009": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareFlagMutexCombinations", subtest: "PIB-009"}}},
		"PIB-010": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareFlagMutexCombinations", subtest: "PIB-010"}}},
		"PIB-011": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareCheckModeFlagMutex", subtest: "PIB-011"}}},
		"PIB-012": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareCheckModeFlagMutex", subtest: "PIB-012"}}},
		"PIB-013": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareCheckPrecedenceAndExitEnvelope"}}},
		"PIB-014": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB014ExitFourRetiredSourceGuard"}}},
		"PIB-015": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "generate"},
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "yes-preflight"},
			{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "artifact-unsafe"},
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareRawPreimageFailuresPreserveExitClass", subtest: "index-precommit"},
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareRawPreimageFailuresPreserveExitClass", subtest: "index-committed"},
		}},
		"PIB-016": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestAVPGrammarAndSurface", subtest: "AVP-009"}}},
		"PIB-017": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestAVPGrammarAndSurface", subtest: "AVP-010"}}},
		"PIB-018": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "generate"}}},
		"PIB-019": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ReportRenderingAndAbandonSecondRun"}}},
		"PIB-020": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ExactFlagGrammarAndFalseValues"}}},
		"PIB-021": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "generate"}}},
		"PIB-022": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4DefaultSuffixSidecarAndManualStatusCAS", subtest: "suffix-preserves-sidecar-absence"}}},
		"PIB-023": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-023"}}},
		"PIB-024": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ExitThreeAndNoOpPreserveWholeTree", subtest: "no-op-does-not-clean-stale-stage"}}},
		"PIB-025": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "artifact-empty-not-overwritten"}}},
		"PIB-026": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareArtifactAdmissibility", subtest: "PIB-026"}}},
		"PIB-027": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "artifact-unsafe"}}},
		"PIB-028": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareArtifactAdmissibility", subtest: "PIB-028"}}},
		"PIB-029": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareArtifactAdmissibility", subtest: "PIB-029"}}},
		"PIB-030": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-030"}}},
		"PIB-031": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareArtifactAdmissibility", subtest: "PIB-031"}}},
		"PIB-032": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-032"}}},
		"PIB-033": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4DefaultSuffixSidecarAndManualStatusCAS", subtest: "suffix-preserves-sidecar-absence"}}},
		"PIB-034": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "artifact-empty-not-overwritten"}}},
		"PIB-035": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ExitThreeAndNoOpPreserveWholeTree", subtest: "no-op-does-not-clean-stale-stage"}}},
		"PIB-036": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-036"}}},
		"PIB-037": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareArtifactAdmissibility", subtest: "PIB-037"}}},
		"PIB-038": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "artifact-unstable"}}},
		"PIB-039": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestAVPReadinessAndOutput", subtest: "AVP-035"}}},
		"PIB-040": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareArtifactAdmissibility", subtest: "PIB-040"}}},
		"PIB-041": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "generate"}}},
		"PIB-042": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-042"}}},
		"PIB-043": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-043"}}},
		"PIB-044": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB044DispositionTableTotality"}}},
		"PIB-045": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-045"}}},
		"PIB-046": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "manual"}}},
		"PIB-047": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-047"}}},
		"PIB-048": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-048"}}},
		"PIB-049": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-049"}}},
		"PIB-050": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-050"}}},
		"PIB-051": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7PIB399ManualStatusUsesRootedDurableWriterOnly"}}},
		"PIB-052": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7PIB399ManualStatusUsesRootedDurableWriterOnly"}}},
		"PIB-053": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-053"}}},
		"PIB-054": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareArtifactAdmissibility", subtest: "PIB-054"}}},
		"PIB-055": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "feature-state-below-defined"}}},
		"PIB-056": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-056"}}},
		"PIB-057": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-057"}}},
		"PIB-058": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "status-malformed"}}},
		"PIB-059": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB059ManualPathConstructsNoProvider"}}},
		"PIB-060": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4RegenerateArchivesPriorBytes"}}},
		"PIB-061": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "artifact-unsafe"}}},
		"PIB-062": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestIntentArchiveAppendPrecommitStorageErrorRemainsExitThree"}}},
		"PIB-063": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestIntentArchiveBlobPublicationReportsReuseWithoutFalseOrphan"}}},
		"PIB-064": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestIntentArchiveAppendRefusesCorruptExistingObjectWithoutOverwrite"}}},
		"PIB-065": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestIntentArchiveAppendCollisionAndGlobalRehydrate"}}},
		"PIB-066": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowRegenerateContracts", subtest: "PIB-066"}}},
		"PIB-067": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowRegenerateContracts", subtest: "PIB-067"}}},
		"PIB-068": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-068"}}},
		"PIB-069": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "archive-generation-duplicate"}}},
		"PIB-070": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowRegenerateContracts", subtest: "PIB-070"}}},
		"PIB-071": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7AWOwnedCorruptRouteGuard"}}},
		"PIB-072": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APDryRunContracts", subtest: "PIB-461"}}},
		"PIB-073": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APDryRunContracts", subtest: "PIB-461"}}},
		"PIB-074": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "dry-run"}}},
		"PIB-075": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APDryRunContracts", subtest: "PIB-461"}}},
		"PIB-076": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-076"}}},
		"PIB-077": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APDryRunContracts", subtest: "PIB-462"}}},
		"PIB-078": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4DryRunSkipsProviderGitAuthorityAndWrites"}}},
		"PIB-079": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7PIB440DryRunModesAndRefusalsSkipAllMutatingEffects", subtest: "pending-journal-not-evaluated"}}},
		"PIB-080": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4DryRunSkipsProviderGitAuthorityAndWrites"}}},
		"PIB-081": {targets: []s7FixtureTarget{
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestJournalFailureLeavesCanonicalTreeByteIdentical"},
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4StagedValidationRefusalIsZeroWrite"},
		}},
		"PIB-082": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowStagedOutputValidationRefusals", subtest: "PIB-082"}}},
		"PIB-083": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowStagedOutputValidationRefusals", subtest: "PIB-083"}}},
		"PIB-084": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowStagedOutputValidationRefusals", subtest: "PIB-084"}}},
		"PIB-085": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowStagedOutputValidationRefusals", subtest: "PIB-085"}}},
		"PIB-086": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowStagedOutputValidationRefusals", subtest: "PIB-086"}}},
		"PIB-087": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowStagedOutputValidationRefusals", subtest: "PIB-087"}}},
		"PIB-088": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowStagedOutputValidationRefusals", subtest: "PIB-088"}}},
		"PIB-089": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestStageV1ThroughV6AndArtifactSensitivity", subtest: "v6-identity"}}},
		"PIB-090": {targets: []s7FixtureTarget{
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestExecutePublishesFixedOrderStatusLastAndRetainsAuthority"},
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4StagesBeforeRevalidationAndPublishesStatusLast"},
		}},
		"PIB-091": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4RevalidationFailureRetainsStageAndConcurrentBytes"}}},
		"PIB-092": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4TerminalJournalRecoveryAndStaleStageCleanup"}}},
		"PIB-093": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestExactModesUnderUmask"}}},
		"PIB-094": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "local-lane-not-ignored"}}},
		"PIB-095": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "local-lane-not-ignored"}}},
		"PIB-096": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestDurableWriterSequenceCASAndFaultCleanup", subtest: "sequence"}}},
		"PIB-097": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestProductionSourceHasNoPathWritersOrForbiddenJournalFields"}}},
		"PIB-098": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4RevalidationFailureRetainsStageAndConcurrentBytes"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestJournalFailureLeavesCanonicalTreeByteIdentical"},
		}},
		"PIB-099": {targets: []s7FixtureTarget{
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestExecutePublishesFixedOrderStatusLastAndRetainsAuthority"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestNamedInjectionSeamsReachPublicationBoundaries"},
		}},
		"PIB-100": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4RevalidationFailureRetainsStageAndConcurrentBytes"}}},
		"PIB-101": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestExecuteSetAndPerEntryCAS", subtest: "set-level"}}},
		"PIB-102": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestExecuteSetAndPerEntryCAS", subtest: "set-level"}}},
		"PIB-103": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB103ConcurrentWindowDisclosure"}}},
		"PIB-104": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4RevalidationFailureRetainsStageAndConcurrentBytes"}}},
		"PIB-105": {targets: []s7FixtureTarget{{dir: "internal/intentlock", pkg: "intentlock", test: "TestAcquireSuccessRevalidatesUnchangedOriginalPath"}}},
		"PIB-106": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-106"}}},
		"PIB-107": {targets: []s7FixtureTarget{{dir: "internal/gitutil", pkg: "gitutil", test: "TestPrepareGitStateThreadsOneG1AndExactG2G3G4"}}},
		"PIB-108": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestExecutePublishesFixedOrderStatusLastAndRetainsAuthority"}}},
		"PIB-109": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestNamedInjectionSeamsReachPublicationBoundaries"}}},
		"PIB-110": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestExecuteRollbackAndOrphanResult"}}},
		"PIB-111": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPersistJournalPostRenameFailureRetainsEvidence"}}},
		"PIB-112": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestRollbackFinalSetDetectsEarlierRestoreRewrittenAfterLaterUndo"}}},
		"PIB-113": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4TerminalJournalRecoveryAndStaleStageCleanup"}}},
		"PIB-114": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestRecoveryCleanupRemovesEveryOwnedStageAndNothingElse"}}},
		"PIB-115": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestRecoveryCleanupRemovesEveryOwnedStageAndNothingElse"}}},
		"PIB-116": {targets: []s7FixtureTarget{{dir: "internal/intentlock", pkg: "intentlock", test: "TestAcquireCreatesNoResidueAndReleasePermitsReacquire"}}},
		"PIB-117": {targets: []s7FixtureTarget{{dir: "internal/intentlock", pkg: "intentlock", test: "TestProcessDeathReleasesAuthorityWithoutArtifact"}}},
		"PIB-118": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB118CrashPhaseTwoOrphanBlobs"}}},
		"PIB-119": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowRecoveryCrashPhaseEvidence", subtest: "PIB-119"}}},
		"PIB-120": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowRecoveryCrashPhaseEvidence", subtest: "PIB-120"}}},
		"PIB-121": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowRecoveryCrashPhaseEvidence", subtest: "PIB-121"}}},
		"PIB-122": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowRecoveryCrashPhaseEvidence", subtest: "PIB-122"}}},
		"PIB-123": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowRecoveryCrashPhaseEvidence", subtest: "PIB-123"}}},
		"PIB-124": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestCaptureLockContentionAcrossProcesses"}}},
		"PIB-125": {targets: []s7FixtureTarget{{dir: "internal/intentlock", pkg: "intentlock", test: "TestRealProcessContentionAndExplicitRelease"}}},
		"PIB-126": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestRecoveryDivergenceAndNonPrefixPreserveEvidence", subtest: "third-party"}}},
		"PIB-127": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "state-refused"}}},
		"PIB-128": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareLifecycleAndRecovery", subtest: "PIB-128"}}},
		"PIB-129": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-129"}}},
		"PIB-130": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestAVPCompatibility", subtest: "AVP-064"}}},
		"PIB-131": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-131"}}},
		"PIB-132": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-132"}}},
		"PIB-133": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestDoctorCLID9SelectionWarningExitAndFixNoWrite"}}},
		"PIB-134": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7PIB445DoctorD9SourceGuardAndWrongInput", subtest: "baseline"}}},
		"PIB-135": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestDoctorCLID9SelectionWarningExitAndFixNoWrite"}}},
		"PIB-136": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "doctor-D1-through-D8"}}},
		"PIB-137": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-137"}}},
		"PIB-138": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4DefaultSuffixSidecarAndManualStatusCAS", subtest: "legacy-missing-artifacts-directory"}}},
		"PIB-139": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "bundle-untracked-in-git"}}},
		"PIB-140": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-140"}}},
		"PIB-141": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-141"}}},
		"PIB-142": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-142"}}},
		"PIB-143": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-143"}}},
		"PIB-144": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-144"}}},
		"PIB-145": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-145"}}},
		"PIB-146": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-146"}}},
		"PIB-147": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-147"}}},
		"PIB-148": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIB148PIB149PIB151RenameFinalGate", subtest: "PIB-148-final-symlink"}}},
		"PIB-149": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIB148PIB149PIB151RenameFinalGate", subtest: "PIB-149-final-directory"}}},
		"PIB-150": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIB150RenameFinalGateRefusesFIFOWithoutOpeningIt", subtest: "PIB-150-final-fifo-no-open"}}},
		"PIB-151": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIB148PIB149PIB151RenameFinalGate", subtest: "PIB-151-artifacts-symlink"}}},
		"PIB-152": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6PrepareContractRows", subtest: "PIB-152-land-stages-intent-archive"}}},
		"PIB-153": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6PrepareContractRows", subtest: "PIB-153-record-ignores-intent-archive"}}},
		"PIB-154": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6PrepareContractRows", subtest: "PIB-154-write-target-constructor-closure/approved-slug-constructor-contract"}}},
		"PIB-155": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6AtomicClaimPolaritySensitivity"}}},
		"PIB-156": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6PrepareContractRows", subtest: "PIB-156-unsafe-slug-is-not-echoed"}}},
		"PIB-157": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6PrepareContractRows", subtest: "PIB-157-oversized-provider-output-zero-mutation"}}},
		"PIB-158": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB158GuardAndSensitivity"}}},
		"PIB-159": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB159GuardAndSensitivity"}}},
		"PIB-160": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestIntentArchiveBlobPublicationBoundaryAndCanonicalNoOp"}}},
		"PIB-161": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestIntentArchiveGenerationGoldenAndCanonicalWire"}}},
		"PIB-162": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestComputeGenerationID_Determinism"}}},
		"PIB-163": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7AWOwnedCorruptRouteGuard"}}},
		"PIB-164": {targets: []s7FixtureTarget{
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestJournalWireHasNoForbiddenTransactionFields"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-298"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-299-unknown-top"},
		}},
		"PIB-165": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestIntentArchiveSourceGuards"}}},
		"PIB-166": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchiveListTruthAndZeroMutation"}}},
		"PIB-167": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowRegenerateContracts", subtest: "PIB-167"}}},
		"PIB-168": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestIntentArchiveGenerationGoldenAndCanonicalWire"}}},
		"PIB-169": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestIntentArchiveSafeRelativePaths"}}},
		"PIB-170": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestAVPReadinessAndOutput", subtest: "AVP-047"}}},
		"PIB-171": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "generate"}}},
		"PIB-172": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestAVPReadinessAndOutput", subtest: "AVP-039"},
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareCheckJSONAndNoMutation"},
		}},
		"PIB-173": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestAVPReadinessAndOutput", subtest: "AVP-038"},
			{dir: "internal/cli", pkg: "cli", test: "TestS6PrepareContractRows", subtest: "PIB-156-unsafe-slug-is-not-echoed"},
		}},
		"PIB-174": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4StagedValidationRefusalIsZeroWrite"}}},
		"PIB-175": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6AdvisoryGuardSensitivity", subtest: "extra-production-emission"}}},
		"PIB-176": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareCheckPrecedenceAndExitEnvelope"}}},
		"PIB-177": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4TerminalJournalRecoveryAndStaleStageCleanup"}}},
		"PIB-178": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestAVPReadinessAndOutput", subtest: "AVP-046"},
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ReportRenderingAndAbandonSecondRun"},
		}},
		"PIB-179": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB179RefusalRemediationNamesShippedSurface"}}},
		"PIB-180": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RefusalGuardSensitivity", subtest: "extra-production-emission"}}},
		"PIB-181": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestProductionSourceHasNoPathWritersOrForbiddenJournalFields"}}},
		"PIB-182": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6PrepareContractRows", subtest: "PIB-154-write-target-constructor-closure/new-root-rename"}}},
		"PIB-183": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestRenameFinalGateSensitivity"}}},
		"PIB-184": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestGeneratorAPIStructuralPurity"}}},
		"PIB-185": {targets: []s7FixtureTarget{
			{dir: "internal/workflow", pkg: "workflow", test: "TestGeneratorPurityGuardSensitivity", subtest: "filesystem call"},
			{dir: "internal/workflow", pkg: "workflow", test: "TestGeneratorPurityGuardSensitivity", subtest: "writer input"},
			{dir: "internal/workflow", pkg: "workflow", test: "TestGeneratorPurityGuardSensitivity", subtest: "sink callback"},
		}},
		"PIB-186": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-186"}}},
		"PIB-187": {targets: []s7FixtureTarget{{dir: "internal/intent", pkg: "intent", test: "TestAVPStructuralClassification", subtest: "AVP-023-read-is-cap-plus-one-bounded"}}},
		"PIB-188": {targets: []s7FixtureTarget{
			{dir: "internal/workflow", pkg: "workflow", test: "TestS7PIB419ProviderSuccessFailureRetryHaveNoRawSink", subtest: "retry-then-success"},
			{dir: "internal/workflow", pkg: "workflow", test: "TestS7PIB419ProviderSuccessFailureRetryHaveNoRawSink", subtest: "provider-failure"},
		}},
		"PIB-189": {targets: []s7FixtureTarget{
			{dir: "internal/workflow", pkg: "workflow", test: "TestGeneratorPurityGuardSensitivity", subtest: "retry store field"},
			{dir: "internal/workflow", pkg: "workflow", test: "TestS7PIB420PureGeneratorRetryConstructionGuardAndWrongInput"},
		}},
		"PIB-190": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestPureGeneratorDoesNotPersistProviderOrPromptText"}}},
		"PIB-191": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB191NoUnboundedRuntimeClaim"}}},
		"PIB-192": {targets: []s7FixtureTarget{
			{dir: "internal/workflow", pkg: "workflow", test: "TestPureGeneratorTransportAndValidationFallback", subtest: "transport"},
			{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "provider-fallback-heuristic"},
		}},
		"PIB-193": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7PIB437AuthorityDurationDocsGuardAndWrongInput", subtest: "adr-filesystem-bound"}}},
		"PIB-194": {targets: []s7FixtureTarget{
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowStagedOutputValidationRefusals", subtest: "PIB-082"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowStagedOutputValidationRefusals", subtest: "PIB-083"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestStageV1ThroughV6AndArtifactSensitivity", subtest: "v6-identity"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestStageV1ThroughV6AndArtifactSensitivity", subtest: "v5-encoding-json-object-key-semantics"},
		}},
		"PIB-195": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-140"},
			{dir: "internal/cli", pkg: "cli", test: "TestAVPReadinessAndOutput", subtest: "AVP-031"},
		}},
		"PIB-196": {targets: []s7FixtureTarget{
			{dir: "internal/workflow", pkg: "workflow", test: "TestPureGeneratorsDefaultHeuristicWithoutProvider"},
			{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "provider-not-configured"},
		}},
		"PIB-197": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestPureGeneratorTransportAndValidationFallback", subtest: "transport"}}},
		"PIB-198": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-198"}}},
		"PIB-199": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-199"}}},
		"PIB-200": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-200"}}},
		"PIB-201": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestAVPZeroMutationAndPrivacy", subtest: "AVP-053"}}},
		"PIB-202": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-140"}}},
		"PIB-203": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestAVPReadinessAndOutput", subtest: "AVP-046"}}},
		"PIB-204": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestAVPReadinessAndOutput", subtest: "AVP-038"},
			{dir: "internal/cli", pkg: "cli", test: "TestAVPReadinessAndOutput", subtest: "AVP-041"},
		}},
		"PIB-205": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestAVPReadinessAndOutput", subtest: "AVP-031"}}},
		"PIB-206": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowCheckInsidePublicationWindow"}}},
		"PIB-207": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-207"}}},
		"PIB-208": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-208"}}},
		"PIB-209": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5CycleCompatibilityRows", subtest: "PIB-209"}}},
		"PIB-210": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-210"}}},
		"PIB-211": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-211"}}},
		"PIB-212": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-212"}}},
		"PIB-213": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5NonInvalidationSourceRows", subtest: "PIB-213"}}},
		"PIB-214": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5NonInvalidationSourceRows", subtest: "PIB-214"}}},
		"PIB-215": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB215GuardAndSensitivity"}}},
		"PIB-216": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB216GuardAndSensitivity"}}},
		"PIB-217": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB217GuardAndSensitivity"}}},
		"PIB-218": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB218GuardAndSensitivity"}}},
		"PIB-219": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB219GuardAndSensitivity"}}},
		"PIB-220": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB220GuardAndSensitivity"}}},
		"PIB-221": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5PlatformRows", subtest: "PIB-221"}}},
		"PIB-222": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBUnsupportedPlatformRuntimeGolden", subtest: "PIB-222"}}},
		"PIB-223": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5PlatformRows", subtest: "PIB-223"}}},
		"PIB-224": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB224GuardAndSensitivity"}}},
		"PIB-225": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB225GuardAndSensitivity"}}},
		"PIB-226": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6VocabularyDerivationSensitivity", subtest: "ranked-class-reordered"}}},
		"PIB-227": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6AdvisoryGuardSensitivity", subtest: "direct-struct-emission"}}},
		"PIB-228": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RefusalGuardSensitivity", subtest: "direct-struct-emission"}}},
		"PIB-229": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB229GuardAndSensitivity"}}},
		"PIB-230": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB230GuardAndSensitivity"}}},
		"PIB-231": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB231GuardAndSensitivity"}}},
		"PIB-232": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestS6InjectionSeamsNilAtInitialization", subtest: "PIB-232-cli-runtime-nil"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestS6InjectionSeamsNilAtInitialization", subtest: "PIB-232-intentpub-runtime-nil"},
			{dir: "internal/store", pkg: "store", test: "TestS6InjectionSeamsNilAtInitialization", subtest: "PIB-232-store-runtime-nil"},
			{dir: "internal/intentlock", pkg: "intentlock", test: "TestS6InjectionSeamsNilAtInitialization", subtest: "PIB-232-intentlock-runtime-nil"},
		}},
		"PIB-233": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ExitThreeAndNoOpPreserveWholeTree", subtest: "request-refusal-does-not-clean-stale-stage"},
			{dir: "internal/cli", pkg: "cli", test: "TestAVPGrammarAndSurface", subtest: "AVP-007"},
		}},
		"PIB-234": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "manual"}}},
		"PIB-235": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareFlagMutexCombinations", subtest: "PIB-235"}}},
		"PIB-236": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "manual"},
			{dir: "internal/cli", pkg: "cli", test: "TestS7ARPrepareGrammarGuard", subtest: "PIB-520"},
		}},
		"PIB-237": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ProviderGateReleasesAuthority"}}},
		"PIB-238": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4AbandonPreviewAndMove"}}},
		"PIB-239": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestS7AQFlagContracts", subtest: "PIB-500"},
			{dir: "internal/cli", pkg: "cli", test: "TestS7AQFlagContracts", subtest: "PIB-501"},
		}},
		"PIB-240": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "dry-run"},
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ExactFlagGrammarAndFalseValues"},
		}},
		"PIB-241": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4RegenerateDeadlineNamesScopeAndArtifact"}}},
		"PIB-242": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4StagedValidationRefusalIsZeroWrite"}}},
		"PIB-243": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4GenerateManualDryRunAndYesPreflight", subtest: "yes-preflight"},
			{dir: "internal/cli", pkg: "cli", test: "TestS7AQFlagContracts", subtest: "PIB-502"},
		}},
		"PIB-244": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestS7ARPrepareGrammarGuard", subtest: "PIB-520"},
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ExactFlagGrammarAndFalseValues"},
		}},
		"PIB-245": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "incoherent-bundle-gap"}}},
		"PIB-246": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "incoherent-bundle-gap"}}},
		"PIB-247": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "incoherent-bundle-gap"}}},
		"PIB-248": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "incoherent-bundle-gap"}}},
		"PIB-249": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB249IncoherentGapMessage"}}},
		"PIB-250": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB250CoherenceTableTotality"}}},
		"PIB-251": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4DefaultSuffixSidecarAndManualStatusCAS", subtest: "suffix-preserves-sidecar-absence"}}},
		"PIB-252": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB252DefaultModePreservesPresentEmptySidecar"}}},
		"PIB-253": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "incoherent-bundle-gap"}}},
		"PIB-254": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "incoherent-bundle-gap"}}},
		"PIB-255": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-255"}}},
		"PIB-256": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareDefaultModePreservation", subtest: "PIB-256"}}},
		"PIB-257": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-257"}}},
		"PIB-258": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB258PublicationUnitClaims"}}},
		"PIB-259": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareLifecycleAndRecovery", subtest: "PIB-259"}}},
		"PIB-260": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareLifecycleAndRecovery", subtest: "PIB-260"}}},
		"PIB-261": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareFeaturesRefreshUsesCapturedIdentity", subtest: "concurrent-edit"}}},
		"PIB-262": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ExitThreeAndNoOpPreserveWholeTree", subtest: "redaction-refusal-does-not-clean-or-stage"}}},
		"PIB-263": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowArchiveRedactionContracts", subtest: "PIB-263"}}},
		"PIB-264": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowArchiveRedactionContracts", subtest: "PIB-264"}}},
		"PIB-265": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowArchiveRedactionContracts", subtest: "PIB-265"}}},
		"PIB-266": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestIntentArchiveSourceGuards"}}},
		"PIB-267": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB267NoRedactionOverride"}}},
		"PIB-268": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APDryRunContracts", subtest: "PIB-461"}}},
		"PIB-269": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB269RecoveryPendingMessage"}}},
		"PIB-270": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APAbandonContracts", subtest: "PIB-450"}}},
		"PIB-271": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestS7APAbandonContracts", subtest: "PIB-450"},
			{dir: "internal/cli", pkg: "cli", test: "TestS7APAbandonContracts", subtest: "PIB-451"},
		}},
		"PIB-272": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APAbandonContracts", subtest: "PIB-451"}}},
		"PIB-273": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4AbandonPreviewAndMove"},
			{dir: "internal/cli", pkg: "cli", test: "TestS7AUAbandonBooleanDomainContracts"},
		}},
		"PIB-274": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APAbandonContracts", subtest: "PIB-449"}}},
		"PIB-275": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestUndoCASPreservesThirdPartyBytesAndEvidence"}}},
		"PIB-276": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB276UndoIdentityIsAbsence"}}},
		"PIB-277": {targets: []s7FixtureTarget{
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestRollbackRestoresArchiveAndRawMetadataPreimages"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestRegeneratePublishesIndexImmediatelyBeforeStatus"},
		}},
		"PIB-278": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestRollbackFinalSetDetectsEarlierRestoreRewrittenAfterLaterUndo"}}},
		"PIB-279": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APPrepareGitRuntime", subtest: "PIB-476"}}},
		"PIB-280": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "local-lane-not-ignored"}}},
		"PIB-281": {targets: []s7FixtureTarget{{dir: "internal/gitutil", pkg: "gitutil", test: "TestPrepareGitStateThreadsOneG1AndExactG2G3G4"}}},
		"PIB-282": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APPrepareGitRuntime", subtest: "PIB-475"}}},
		"PIB-283": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB283LaneGateCallSite"}}},
		"PIB-284": {targets: []s7FixtureTarget{{dir: "internal/intentlock", pkg: "intentlock", test: "TestProcessDeathReleasesAuthorityWithoutArtifact"}}},
		"PIB-285": {targets: []s7FixtureTarget{{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB418AuthoritySourceAndDocsRejectLegacyLockPrimitives"}}},
		"PIB-286": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-286"}}},
		"PIB-287": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBGoldenProvenance", subtest: "unsupported-platform-source-contract"}}},
		"PIB-288": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5PlatformRows", subtest: "PIB-222"}}},
		"PIB-289": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5PlatformRows", subtest: "PIB-223"}}},
		"PIB-290": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestS7PIB395RealCLIContenderExitsThreeUnderHeldRoot"},
			{dir: "internal/intentlock", pkg: "intentlock", test: "TestRealProcessContentionAndExplicitRelease"},
		}},
		"PIB-291": {targets: []s7FixtureTarget{
			{dir: "internal/intentlock", pkg: "intentlock", test: "TestProcessDeathReleasesAuthorityWithoutArtifact"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowRecoveryCrashPhaseEvidence", subtest: "PIB-119"},
		}},
		"PIB-292": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareManualContracts", subtest: "PIB-292"}}},
		"PIB-293": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestRecoveryCP5CP6CP8Fixtures", subtest: "cp8-journal-cleared"}}},
		"PIB-294": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPrepareLifecycleAndRecovery", subtest: "PIB-294"}}},
		"PIB-295": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestNamedInjectionSeamsReachPublicationBoundaries"}}},
		"PIB-296": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestExecuteSetAndPerEntryCAS", subtest: "per-entry"}}},
		"PIB-297": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestRecoveryDivergenceAndNonPrefixPreserveEvidence", subtest: "mixed-arbitrary-order"}}},
		"PIB-298": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-298"}}},
		"PIB-299": {targets: []s7FixtureTarget{
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-299-unknown-top"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-299-unknown-entry"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-299-unknown-identity"},
		}},
		"PIB-300": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-300"}}},
		"PIB-301": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-301"}}},
		"PIB-302": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-302"}}},
		"PIB-303": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-303"}}},
		"PIB-304": {targets: []s7FixtureTarget{
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-304-duplicate-id"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-304-null-entries"},
		}},
		"PIB-305": {targets: []s7FixtureTarget{
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-298"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-300"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-301"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-302"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestPIBRowJournalStrictDecoderBinds", subtest: "PIB-303"},
		}},
		"PIB-306": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestIdentityExactnessModesBoundsAndKinds"}}},
		"PIB-307": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestInvalidJournalRecoveryPerformsNoRootMutation"}}},
		"PIB-308": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestProductionSourceHasNoPathWritersOrForbiddenJournalFields"}}},
		"PIB-309": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestProductionSourceHasNoPathWritersOrForbiddenJournalFields"}}},
		"PIB-310": {targets: []s7FixtureTarget{
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestCaptureUsesComponentWalkAndRejectsAncestorSubstitution", subtest: "raced-symlink"},
			{dir: "internal/intentpub", pkg: "intentpub", test: "TestS7PIB406HeldRootRedirectsNeverEscapeAuthority", subtest: "ancestor-substitution-is-detected-after-rooted-open"},
		}},
		"PIB-311": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestProductionWriteRequestsDeclareExplicitRoles"}}},
		"PIB-312": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB312DurableWriterParity"}}},
		"PIB-313": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestProductionSourceHasNoPathWritersOrForbiddenJournalFields"}}},
		"PIB-314": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestFinalVerificationPreservesDivergence"}}},
		"PIB-315": {targets: []s7FixtureTarget{{dir: "internal/intentpub", pkg: "intentpub", test: "TestExecutePublishesFixedOrderStatusLastAndRetainsAuthority"}}},
		"PIB-316": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowArchiveEvidenceContracts", subtest: "PIB-316"}}},
		"PIB-317": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowArchiveEvidenceContracts", subtest: "PIB-317"}}},
		"PIB-318": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowArchiveEvidenceContracts", subtest: "PIB-318"}}},
		"PIB-319": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowArchiveEvidenceContracts", subtest: "PIB-319"}}},
		"PIB-320": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowArchiveEvidenceContracts", subtest: "PIB-320"}}},
		"PIB-321": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9RemovedJournalAndFreshCloneDoNotInventLoss", subtest: "removed-journal"}}},
		"PIB-322": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9RemovedJournalAndFreshCloneDoNotInventLoss", subtest: "fresh-clone-healthy-archive"}}},
		"PIB-323": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestDoctorD9DisclosureRows", subtest: "PIB-323"}}},
		"PIB-324": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5LateCrashAndLifecycleRows", subtest: "PIB-324"}}},
		"PIB-325": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5LateCrashAndLifecycleRows", subtest: "PIB-325"}}},
		"PIB-326": {targets: []s7FixtureTarget{
			{dir: "internal/gitutil", pkg: "gitutil", test: "TestS7APGitContracts", subtest: "PIB-472"},
			{dir: "internal/gitutil", pkg: "gitutil", test: "TestS7APGitContracts", subtest: "PIB-473"},
		}},
		"PIB-327": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "workspace-not-git"}}},
		"PIB-328": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "workspace-not-git"}}},
		"PIB-329": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "local-lane-unverifiable"}}},
		"PIB-330": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowRegenerateContracts", subtest: "PIB-330"}}},
		"PIB-331": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-331"}}},
		"PIB-332": {targets: []s7FixtureTarget{
			{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-332-unknown-top"},
			{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-332-unknown-generation"},
		}},
		"PIB-333": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "archive-index-version-unsupported"}}},
		"PIB-334": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "archive-index-foreign"}}},
		"PIB-335": {targets: []s7FixtureTarget{
			{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-335-null-generations"},
			{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-335-null-replaced"},
		}},
		"PIB-336": {targets: []s7FixtureTarget{
			{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-336-duplicate-key"},
			{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-336-malformed-generation-id"},
		}},
		"PIB-337": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-337"}}},
		"PIB-338": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-338"}}},
		"PIB-339": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-339"}}},
		"PIB-340": {targets: []s7FixtureTarget{{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-340"}}},
		"PIB-341": {targets: []s7FixtureTarget{
			{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-332-unknown-top"},
			{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-332-unknown-generation"},
			{dir: "internal/store", pkg: "store", test: "TestPIBRowIntentArchiveIndexStrictDecoderBinds", subtest: "PIB-341-unknown-replacement"},
		}},
		"PIB-342": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB342UntrackedBundleAdvisory"}}},
		"PIB-343": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7PIB426GitCleanCanRemoveUntrackedIntentArchive", subtest: "fd"}}},
		"PIB-344": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6PrepareContractRows", subtest: "PIB-152-land-stages-intent-archive"}}},
		"PIB-345": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchiveListTruthAndZeroMutation"}}},
		"PIB-346": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchiveListTruthAndZeroMutation"}}},
		"PIB-347": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchivePurgeScopeAndPreview", subtest: "missing-scope-is-parse-error"}}},
		"PIB-348": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchivePurgeScopeAndPreview", subtest: "preview-is-exact-and-lock-free"}}},
		"PIB-349": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchivePurgeAuthorityAndPendingJournal", subtest: "contention"}}},
		"PIB-350": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB350PurgeRefusesPendingJournal"}}},
		"PIB-351": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchivePurgeIdempotencyGenerationAllAndSharedHash", subtest: "blob-idempotency-and-secret-remediation"}}},
		"PIB-352": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchiveCrashBoundariesAndRecovery", subtest: "pending-index-before-remove-recovers"}}},
		"PIB-353": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchiveCrashBoundariesAndRecovery", subtest: "before-index-rewrite-is-zero-write"}}},
		"PIB-354": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchivePurgeIdempotencyGenerationAllAndSharedHash", subtest: "generation-preserves-identity"}}},
		"PIB-355": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchivePurgeIdempotencyGenerationAllAndSharedHash", subtest: "shared-hash-global-claim-and-all"},
			{dir: "internal/store", pkg: "store", test: "TestIntentArchiveAllSelectsEveryReferenceAndBlob"},
		}},
		"PIB-356": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchiveListGlobalAvailabilityAndCompleteObservations"},
			{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9ArchiveEvidenceClassesAndRoutes"},
		}},
		"PIB-357": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchivePurgeIdempotencyGenerationAllAndSharedHash", subtest: "shared-hash-global-claim-and-all"}}},
		"PIB-358": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchivePurgeIdempotencyGenerationAllAndSharedHash", subtest: "shared-hash-global-claim-and-all"}}},
		"PIB-359": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchiveOrphanCASAndRevalidation", subtest: "blob-identity"},
			{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchiveOrphanCASAndRevalidation", subtest: "index-preimage"},
		}},
		"PIB-360": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchivePurgeIdempotencyGenerationAllAndSharedHash", subtest: "blob-idempotency-and-secret-remediation"}}},
		"PIB-361": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestFeatureIntentArchiveQuietHistoryPathsAndSourceGuards"}}},
		"PIB-362": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7ARExitSixRouteGuard", subtest: "PIB-508"}}},
		"PIB-363": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APAbandonContracts", subtest: "PIB-449"}}},
		"PIB-364": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS7APAbandonContracts", subtest: "PIB-452"}}},
		"PIB-365": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ProviderGateReleasesAuthority"}}},
		"PIB-366": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestS7AUAbandonBooleanDomainContracts"},
			{dir: "internal/cli", pkg: "cli", test: "TestS7APAbandonContracts", subtest: "PIB-450"},
		}},
		"PIB-367": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ReportRenderingAndAbandonSecondRun"}}},
		"PIB-368": {targets: []s7FixtureTarget{
			{dir: "internal/workflow", pkg: "workflow", test: "TestPureGeneratorRegenerateAuthority", subtest: "no-provider-refuses-without-call-or-output"},
			{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4ProviderGateReleasesAuthority"},
		}},
		"PIB-369": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestPureGeneratorRegenerateAuthority", subtest: "provider-failure-refuses-without-partial-output"}}},
		"PIB-370": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS4RegenerateDeadlineNamesScopeAndArtifact"}}},
		"PIB-371": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "provider-deadline-cascade"}}},
		"PIB-372": {targets: []s7FixtureTarget{
			{dir: "internal/workflow", pkg: "workflow", test: "TestPureGeneratorRegenerateAuthority", subtest: "explicit-heuristic-opt-in"},
			{dir: "internal/cli", pkg: "cli", test: "TestS6CatalogReachabilityFixtures", subtest: "regenerate-heuristic-allowed"},
		}},
		"PIB-373": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB373DeadlineCascadeNamesOneExpiry"}}},
		"PIB-374": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB374AllowHeuristicHelpSentence"}}},
		"PIB-375": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB375NoHeuristicConfigRoute"}}},
		"PIB-376": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestS7PIB446RawResponseStructuralGuardAndWrongInput", subtest: "forbidden-retry-store-field"}}},
		"PIB-377": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB377NoTimingFieldsInReports"}}},
		"PIB-378": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5ProvenanceBoundaryRows", subtest: "PIB-378"}}},
		"PIB-379": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestPrepareS5LateCrashAndLifecycleRows", subtest: "PIB-379"}}},
		"PIB-380": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9ConnectedCapabilitySpiesRecordZeroProbesProcessesAndWrites"}}},
		"PIB-381": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestPIBRowPIB381DoctorNeverObservesLiveAuthority"}}},
		"PIB-382": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9PrepareEvidenceTaxonomyAndOrdering"}}},
		"PIB-383": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9PrepareEvidenceTaxonomyAndOrdering"}}},
		"PIB-384": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9ArchiveEvidenceClassesAndRoutes"}}},
		"PIB-385": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9MalformedAndUnsafeEvidenceFailsClosed", subtest: "corrupt-index-offers-list-only"}}},
		"PIB-386": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9CleanWorkspaceAndLostJournalBoundary"}}},
		"PIB-387": {targets: []s7FixtureTarget{{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9RegistryOrderAndTaxonomySensitivity"}}},
		"PIB-388": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB388GuardAndSensitivity"}}},
		"PIB-389": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB389GuardAndSensitivity"}}},
		"PIB-390": {targets: []s7FixtureTarget{{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB390GuardAndSensitivity"}}},
		"PIB-391": {targets: []s7FixtureTarget{
			{dir: "internal/cli", pkg: "cli", test: "TestS6GoldenWiringSensitivities", subtest: "record-call"},
			{dir: "internal/cli", pkg: "cli", test: "TestPreparePIBPreChangeGoldens", subtest: "PIB-391-routing-provenance-and-immutability"},
		}},
		"PIB-392": {targets: []s7FixtureTarget{
			{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB416LinuxRootFilesystemClassificationTable"},
			{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB416DarwinRootFilesystemClassificationTable"},
			{dir: "internal/cli", pkg: "cli", test: "TestS7PIB416DeniedFilesystemClassesReachPublicCLIReports"},
		}},
		"PIB-393": {targets: []s7FixtureTarget{{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB418AuthoritySourceAndDocsRejectLegacyLockPrimitives"}}},
		"PIB-394": {targets: []s7FixtureTarget{{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB432PrepareOwnedAuthorityAndFrozenRescapParity"}}},
	}
}

// pibGuardSensitivityRegistry maps every `G` row of the shipped matrix to the
// body that mutates its guarded input and asserts the same validator rejects it,
// *and* to the validator symbol that body must assert. The key set is checked
// against the Kind column at run time, never against this literal, so a re-kinded
// row fails here before it can be forgotten.
//
// The S6 rows point at the per-row guards in prepare_pib_row_guards_test.go,
// which run `s6GuardSpecs[id].run` on the shipped input and then require
// `s6GuardSpecs[id].sensitivity` — the row's own wrong-input fixture — to be
// rejected by that same validator; `validator: "s6GuardSpecs"` is what binds the
// row to the registry entry keyed by its own ID. The S7 and S1…S5 rows point at
// the accepted wrong-input bodies already shipped with their slices, and name the
// validator those bodies assert.
//
// The `validator` field is not documentation: `pibAssertSensitivityShape` refuses
// a row whose named validator is not the one the body asserts a rejection from,
// which is what stops a row from borrowing a sibling row's fixture.
func pibGuardSensitivityRegistry() map[string]pibSensitivityEntry {
	return map[string]pibSensitivityEntry{
		"PIB-014": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB014ExitFourRetiredSourceGuard"},
			validator:   "pibValidateExitFourRetired",
		},
		"PIB-044": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB044DispositionTableTotality"},
			validator:   "pibValidateDispositionTotality",
		},
		"PIB-136": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB136DoctorGoldenParity"},
			validator:   "preparePIBGoldenDelta",
		},
		"PIB-142": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB142ReportsInferNoPathProvenance"},
			validator:   "validatePrepareS5NoPathProvenanceTokens",
		},
		"PIB-144": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB144GeneratorKeyIsMutatingOnly"},
			validator:   "validatePrepareS5GeneratorSchema",
		},
		"PIB-145": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB145ADR034IsNeverAWritePrecedent"},
			validator:   "validatePrepareS5WritePrecedentClaims",
		},
		"PIB-146": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB146HeuristicSidecarMatchesAnalyze"},
			validator:   "validatePrepareS5HeuristicSidecarParity",
		},
		"PIB-147": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB147ArchiveLayoutCarriesNoProvenance"},
			validator:   "pibValidateNoProvenanceFields",
		},
		"PIB-155": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB155GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-158": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB158GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-159": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB159GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-161": {
			sensitivity: s7FixtureTarget{dir: "internal/store", pkg: "store", test: "TestIntentArchiveCanonicalWireGuardAndSensitivity"},
			validator:   "validateIntentArchiveCanonicalWire",
		},
		"PIB-164": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB164JournalCarriesNoWallClockOrPhase"},
			validator:   "pibValidateJournalWire",
		},
		"PIB-169": {
			sensitivity: s7FixtureTarget{dir: "internal/store", pkg: "store", test: "TestIntentArchiveSafeRelativePaths"},
			validator:   "IntentArchiveBlobRel",
		},
		"PIB-175": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB175AdvisorySelectionIsTotal"},
			validator:   "validateS6Advisories",
		},
		"PIB-180": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB180RefusalStringsCarryNoPointer"},
			validator:   "pibValidateNoDocumentPointer",
		},
		"PIB-186": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB186PhaseGoldenParity"},
			validator:   "preparePIBGoldenDelta",
		},
		"PIB-191": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB191NoUnboundedRuntimeClaim"},
			validator:   "pibValidateNoUnboundedRuntimeClaim",
		},
		"PIB-194": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB194ValidationSetIsExactlySix"},
			validator:   "pibValidateStagedValidationSet",
		},
		"PIB-198": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB198CheckHumanGoldenParity"},
			validator:   "preparePIBGoldenDelta",
		},
		"PIB-199": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB199CheckJSONGoldenParity"},
			validator:   "preparePIBGoldenDelta",
		},
		"PIB-207": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB207CheckPendingGoldenParity"},
			validator:   "preparePIBGoldenDelta",
		},
		"PIB-208": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB208NextGoldenParity"},
			validator:   "preparePIBGoldenDelta",
		},
		"PIB-209": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB209CycleGoldenDigests"},
			validator:   "pibValidateGoldenDigests",
		},
		"PIB-210": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB210PhaseAutoGoldenParity"},
			validator:   "preparePIBGoldenDelta",
		},
		"PIB-211": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB211PhaseManualGoldenParity"},
			validator:   "preparePIBGoldenDelta",
		},
		"PIB-212": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB212CompatibilityGoldenParity"},
			validator:   "preparePIBGoldenDelta",
		},
		"PIB-215": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB215GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-216": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB216GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-217": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB217GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-218": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB218GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-219": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB219GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-220": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB220GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-221": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB221PlatformEnvelopeIsSourceGuarded"},
			validator:   "pibValidateMutatingPlatformGuard",
		},
		"PIB-224": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB224GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-225": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB225GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-226": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB226GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-227": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB227GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-228": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB228GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-229": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB229GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-230": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB230GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-231": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB231GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-232": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB232GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-244": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7ARPrepareGrammarGuard", subtest: "PIB-520"},
			validator:   "validateS7ARPrepareGrammar",
		},
		"PIB-250": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB250CoherenceTableTotality"},
			validator:   "pibValidateCoherenceTable",
		},
		"PIB-258": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB258PublicationUnitClaims"},
			validator:   "pibValidatePublicationUnitClaims",
		},
		"PIB-267": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB267NoRedactionOverride"},
			validator:   "pibValidateNoRedactionOverride",
		},
		"PIB-286": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB286ResourceSurfaceParity"},
			validator:   "preparePIBGoldenDelta",
		},
		"PIB-287": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB287RescapPlatformEnvelope"},
			validator:   "pibValidateRescapEnvelope",
		},
		"PIB-295": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB295CrashTableHasNoPermanentRefusal"},
			validator:   "pibValidateCrashPointTable",
		},
		"PIB-305": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB305JournalBindListIsComplete"},
			validator:   "pibValidateJournalBindList",
		},
		"PIB-309": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB309RenameScanBites"},
			validator:   "pibValidateNoRawRename",
		},
		"PIB-312": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB312DurableWriterParity"},
			validator:   "pibValidateDurableWriterParity",
		},
		"PIB-323": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestDoctorD9DisclosureRows", subtest: "PIB-323"},
			validator:   "validateDoctorD9LossDisclosure",
		},
		"PIB-326": {
			sensitivity: s7FixtureTarget{dir: "internal/gitutil", pkg: "gitutil", test: "TestPIBSensitivityPIB326ClosedGitArgvAllowlist"},
			validator:   "validateS7PIB438GitSources",
		},
		"PIB-341": {
			sensitivity: s7FixtureTarget{dir: "internal/store", pkg: "store", test: "TestIntentArchiveStrictDecoderInjectedKeySensitivity"},
			validator:   "DecodeIntentArchiveIndex",
		},
		"PIB-342": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB342UntrackedBundleAdvisory"},
			validator:   "pibValidateUntrackedBundleAdvisory",
		},
		"PIB-344": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB344LandArchiveSweepIsDisclosed"},
			validator:   "pibValidateLandArchiveDisclosure",
		},
		"PIB-356": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB356AvailabilityClaimsAreExact"},
			validator:   "pibValidateAvailabilityClaims",
		},
		"PIB-361": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB361CommittedBlobDisclosure"},
			validator:   "pibValidateCommittedBlobDisclosure",
		},
		"PIB-362": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB362ExitSixJournalPopulation"},
			validator:   "pibValidateExitSixJournalPopulation",
		},
		"PIB-373": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB373DeadlineCascadeNamesOneExpiry"},
			validator:   "pibValidateDeadlineCascadeText",
		},
		"PIB-376": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB376NoRetryPersistenceOutsideTemp"},
			validator:   "pibValidateNoRetryPersistence",
		},
		"PIB-377": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBRowPIB377NoTimingFieldsInReports"},
			validator:   "pibValidateNoTimingFields",
		},
		"PIB-378": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB378NoAuthorshipEvidenceClaim"},
			validator:   "pibValidateNoAuthorshipClaim",
		},
		"PIB-387": {
			sensitivity: s7FixtureTarget{dir: "internal/workflow", pkg: "workflow", test: "TestDoctorD9RegistryOrderAndTaxonomySensitivity"},
			validator:   "validateDoctorD9Taxonomy",
		},
		"PIB-388": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB388GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-389": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB389GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-390": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB390GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-391": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS6RowPIB391GuardAndSensitivity"},
			validator:   "s6GuardSpecs",
		},
		"PIB-393": {
			sensitivity: s7FixtureTarget{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB418AuthoritySourceAndDocsRejectLegacyLockPrimitives"},
			validator:   "validateS7PIB418AuthorityInputs",
		},
		"PIB-394": {
			sensitivity: s7FixtureTarget{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB432PrepareOwnedAuthorityAndFrozenRescapParity"},
			validator:   "validateS7PIB432Parity",
		},
		"PIB-398": {
			sensitivity: s7FixtureTarget{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB398DirectoryAuthorityConstructionGuardAndWrongInput"},
			validator:   "validateS7PIB398AuthoritySources",
		},
		"PIB-409": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7PIB409WindowsBlockingSelectorGuard"},
			validator:   "validateS7WindowsBlockingSelector",
		},
		"PIB-418": {
			sensitivity: s7FixtureTarget{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB418AuthorityDocsSensitivityDirect"},
			validator:   "validateS7PIB418AuthorityInputs",
		},
		"PIB-420": {
			sensitivity: s7FixtureTarget{dir: "internal/workflow", pkg: "workflow", test: "TestS7PIB420PureGeneratorRetryConstructionGuardAndWrongInput"},
			validator:   "validateS7PureGeneratorPackage",
		},
		"PIB-431": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7PIB431RefusalCatalogRendererParityAndWrongInput"},
			validator:   "validateS6Refusals",
		},
		"PIB-432": {
			sensitivity: s7FixtureTarget{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB432RescapParitySensitivityDirect"},
			validator:   "validateS7PIB432Parity",
		},
		"PIB-434": {
			sensitivity: s7FixtureTarget{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7PIB434AuthorityLifetimeGuardAndWrongInput"},
			validator:   "validateS7PIB434AuthorityLifetime",
		},
		"PIB-437": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7PIB437AuthorityDurationDocsGuardAndWrongInput", subtest: "command-total-bound"},
			validator:   "validateS7PIB437DurationDocs",
		},
		"PIB-438": {
			sensitivity: s7FixtureTarget{dir: "internal/gitutil", pkg: "gitutil", test: "TestS7PIB438CentralGitExecutorGuardAndWrongInput", subtest: "absolute-lane"},
			validator:   "validateS7PIB438GitSources",
		},
		"PIB-445": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7PIB445DoctorD9SourceGuardAndWrongInput", subtest: "reachable-root-open"},
			validator:   "validateS7PIB445Doctor",
		},
		"PIB-446": {
			sensitivity: s7FixtureTarget{dir: "internal/workflow", pkg: "workflow", test: "TestS7PIB446RawResponseStructuralGuardAndWrongInput", subtest: "legacy-retry-store"},
			validator:   "validateS7PureGeneratorPackage",
		},
		"PIB-447": {
			sensitivity: s7FixtureTarget{dir: "internal/store", pkg: "store", test: "TestS7PIB447ArchiveStateMachineSemanticParityAndWrongInput", subtest: "pending-must-still-exist"},
			validator:   "validateS7PIB447Parity",
		},
		"PIB-448": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7PIB448RefusalPrecedenceHelpAndReadOnlyListGuard", subtest: "partial-exit-collapse"},
			validator:   "validateS7PIB448",
		},
		"PIB-456": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7APRootedWriterGuards", subtest: "PIB-456"},
			validator:   "validateS7APRootedWriterSources",
		},
		"PIB-459": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7APDanglingPublicWorkflows", subtest: "PIB-459"},
			validator:   "validateS7APDanglingOwnedSurfaces",
		},
		"PIB-464": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7APDryRunContracts", subtest: "PIB-464"},
			validator:   "validateS7APDryRunPartition",
		},
		"PIB-469": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7APPurgeControlFlowGuard", subtest: "PIB-469"},
			validator:   "validateS7APPurgeControlFlow",
		},
		"PIB-471": {
			sensitivity: s7FixtureTarget{dir: "internal/workflow", pkg: "workflow", test: "TestS7APDoctorD9Contracts", subtest: "PIB-471"},
			validator:   "validateS7APD9HolderClaims",
		},
		"PIB-473": {
			sensitivity: s7FixtureTarget{dir: "internal/gitutil", pkg: "gitutil", test: "TestPIBSensitivityPIB473CompatibilityWrapperEnvelope"},
			validator:   "validateS7APCompatibilityCallGraph",
		},
		"PIB-476": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7APPrepareGitRuntime", subtest: "PIB-476"},
			validator:   "validateS7APGitPrivacy",
		},
		"PIB-477": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7APProvenanceGuard", subtest: "PIB-477"},
			validator:   "validateS7APProducedBySources",
		},
		"PIB-482": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7APReferenceTruthGuard", subtest: "PIB-482"},
			validator:   "validateS7APReferenceTruth",
		},
		"PIB-487": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AQPostRecoveryControlFlowGuard", subtest: "PIB-487"},
			validator:   "validateS7AQTerminalRecoveryControlFlow",
		},
		"PIB-496": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AQRecoverabilityClaimsAreEnvironmentallyQualified"},
			validator:   "validateS7AQRecoverabilityClaims",
		},
		"PIB-497": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AQAbsoluteRootNeverReachesReportsOrProse"},
			validator:   "validateS7AQReportPrivacy",
		},
		"PIB-498": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AQRerunEmittersAreDerivedAndCanonical"},
			validator:   "validateS7AQRerunEmitters",
		},
		"PIB-503": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AQYesSourceGuard", subtest: "PIB-503"},
			validator:   "validateS7AQYesSource",
		},
		"PIB-504": {
			sensitivity: s7FixtureTarget{dir: "internal/intentlock", pkg: "intentlock", test: "TestS7AQAuthorityUsesRetainedDescriptorControl"},
			validator:   "validateS7AQAuthorityControl",
		},
		"PIB-505": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AQStepReferencesResolveToDescribedSemantics"},
			validator:   "validateS7AQStepReferences",
		},
		"PIB-508": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB508ExitSixRouteMapDirect"},
			validator:   "validateS7ARExitSixRoutes",
		},
		"PIB-511": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7ARAbandonGateTableGuard", subtest: "PIB-511"},
			validator:   "validateS7ARAbandonGateTableWithProgram",
		},
		"PIB-518": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7ARPurgeProgressGuard", subtest: "PIB-518"},
			validator:   "validateS7ARPurgeProgressWithModel",
		},
		"PIB-519": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7ARPermanentBlockClaimsGuard", subtest: "PIB-519"},
			validator:   "validateS7ARPermanentBlockClaimsWithState",
		},
		"PIB-524": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7ASX11ClassificationGuardSensitivityTombstonedDivergent"},
			validator:   "validateS7ASX11Classification",
		},
		"PIB-526": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7ASRecoverPendingPurgeCallGraphGuardSensitivityPreparePublish"},
			validator:   "validateS7ASRecoverPendingPurgeCallGraph",
		},
		"PIB-528": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7ASSelectorTotalityGuardSensitivityOrphansRetryWidened"},
			validator:   "validateS7ASSelectorTotality",
		},
		"PIB-533": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7ATGlobalOrphanPredicateSensitivityPerReference"},
			validator:   "validateS7ATGlobalOrphanPredicate",
		},
		"PIB-545": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AUClassificationAuthorityGuard"},
			validator:   "s7AUValidateArchiveAuthority",
		},
		"PIB-546": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB546RecoveryOrderingDirect"},
			validator:   "s7AVValidateRecoveryOrdering",
		},
		"PIB-549": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestPIBSensitivityPIB549AdmissionPredicateDirect"},
			validator:   "s7AVValidateAdmissionPredicate",
		},
		"PIB-551": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AVDispositionTableTotalityGuard"},
			validator:   "s7AVValidateDispositionTotality",
		},
		"PIB-554": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AWClassCollapseGuard"},
			validator:   "s7AWValidateClassCollapseSource",
		},
		"PIB-555": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AWNonDegradationWriteSetGuard"},
			validator:   "s7AWValidateNonDegradationSource",
		},
		"PIB-557": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AWAllEmitterAuthorityGuard"},
			validator:   "s7AWValidateAllCarrier",
		},
		"PIB-558": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AWOwnedCorruptRouteGuard"},
			validator:   "s7AWValidateOwnedCorruptRouteSource",
		},
		"PIB-559": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AWForbiddenCommandTokenizerGuard"},
			validator:   "s7AWValidateTokenBlock",
		},
		"PIB-561": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AXRepairPrecedenceGuard"},
			validator:   "s7AXValidatePrecedenceSource",
		},
		"PIB-564": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AXStageModelGuard"},
			validator:   "s7AXValidateStagePlan",
		},
		"PIB-565": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AXPurgeOutcomeLiteralGuard"},
			validator:   "s7AXValidatePurgeExample",
		},
		"PIB-566": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AXPendingRouteNarrowingGuard"},
			validator:   "s7AXValidatePendingRoute",
		},
		"PIB-567": {
			sensitivity: s7FixtureTarget{dir: "internal/cli", pkg: "cli", test: "TestS7AXRevisionLedgerGuard"},
			validator:   "s7AXNormativeTokenScan",
		},
	}
}
